## 全局抓取时间 间隔
global:
  scrape_interval: 5s

## 抓取配置
scrape_configs:
  ## 定时任务一
  - job_name: node
    static_configs:
      # linux 监控组件
      - targets: ['192.168.5.78:9100']
  # 采集任务名称
  # 定时任务二
  - job_name: 'spring-prometheus-grafana'
    # 采集时间间隔
    scrape_interval: 5s
    # 采集超时时间
    scrape_timeout: 10s
    # 采集数据路径
    metrics_path: '/actuator/prometheus'
    # 采集服务的地址
    static_configs:
      # springboot 应用监控
      - targets: ['192.168.5.78:8088']